#!/bin/sh

set -x

echo "To see the coordinates, use an image viewer like 'Geeqie' with enabled 'Pixel Info' (from 'View' menu)"

INPUT_IMAGE_PATH="${1}"

LEFT_TOP_CORNER_X_COORDINATE="${2}"
LEFT_TOP_CORNER_Y_COORDINATE="${3}"

RIGHT_BOTTOM_CORNER_X_COORDINATE="${4}"
RIGHT_BOTTOM_CORNER_Y_COORDINATE="${5}"

OUTPUT_IMAGE_WIDTH=$(( RIGHT_BOTTOM_CORNER_X_COORDINATE - LEFT_TOP_CORNER_X_COORDINATE ))
OUTPUT_IMAGE_HEIGHT=$(( RIGHT_BOTTOM_CORNER_Y_COORDINATE - LEFT_TOP_CORNER_Y_COORDINATE ))

OUTPUT_IMAGE_PATH_WITHOUT_EXTENSION="${INPUT_IMAGE_PATH%.*}"
INPUT_IMAGE_EXTENSION="${INPUT_IMAGE_PATH##*.}"

convert "${INPUT_IMAGE_PATH}" -crop ${OUTPUT_IMAGE_WIDTH}x${OUTPUT_IMAGE_HEIGHT}+${LEFT_TOP_CORNER_X_COORDINATE}+${LEFT_TOP_CORNER_Y_COORDINATE} "${OUTPUT_IMAGE_PATH_WITHOUT_EXTENSION%.*}-cropped."${INPUT_IMAGE_EXTENSION}""

