#!/bin/sh

#set -x

ORIGINAL_FILE_PATH="${1}"
DIRNAME="$(dirname "${ORIGINAL_FILE_PATH}")"
EXTRACTED_FILENAME="$(basename "${ORIGINAL_FILE_PATH}")"
SEARCHED_STRING="${2}"

printf "%s" "${EXTRACTED_FILENAME}" | grep "${SEARCHED_STRING}" 1>/dev/null 2>&1
if [ $? -ne 0 ]
then
  echo
  exit 1
fi

REPLACING_STRING="${3}"
FILENAME_WITH_REPLACED_STRING="$(printf "%s" "${EXTRACTED_FILENAME}" | sed "s/${SEARCHED_STRING}/${REPLACING_STRING}/g")"
FILE_PATH_WITH_MODIFIED_FILENAME="${DIRNAME}/${FILENAME_WITH_REPLACED_STRING}"

mv "${ORIGINAL_FILE_PATH}" "${FILE_PATH_WITH_MODIFIED_FILENAME}"

